# Run your commands
python optimize_mask_cifar.py --anp-eps 0.1 >> eps1.txtt || echo "command1 failed" >> eps1.txtt
python optimize_mask_cifar.py --anp-eps 0.5 >> eps1.txtt || echo "command2 failed" >> eps1.txtt
python optimize_mask_cifar.py --anp-eps 1.5 >> eps1.txtt || echo "command3 failed" >> eps1.txtt
python optimize_mask_cifar.py --anp-eps 2.0 >> eps1.txtt || echo "command4 failed" >> eps1.txtt
python optimize_mask_cifar.py --anp-eps 2.4 >> eps1.txtt || echo "command5 failed" >> eps1.txtt
python optimize_mask_cifar.py --anp-eps 2.8 >> eps1.txtt || echo "command6 failed" >> eps1.txtt
python optimize_mask_cifar.py --anp-eps 3.2 >> eps1.txtt || echo "command7 failed" >> eps1.txtt
python optimize_mask_cifar.py --anp-eps 3.6 >> eps1.txtt || echo "command8 failed" >> eps1.txtt
python optimize_mask_cifar.py --anp-eps 4.0 >> eps1.txtt || echo "command9 failed" >> eps1.txtt
python optimize_mask_cifar.py --anp-eps 4.4 >> eps1.txtt || echo "command10 failed" >> eps1.txtt
python optimize_mask_cifar.py --anp-eps 4.8 >> eps1.txtt || echo "command11 failed" >> eps1.txtt
python optimize_mask_cifar.py --anp-eps 5.2 >> eps1.txtt || echo "command12 failed" >> eps1.txtt
python optimize_mask_cifar.py --anp-eps 5.6 >> eps1.txtt || echo "command13 failed" >> eps1.txtt
python optimize_mask_cifar.py --anp-eps 6.0 >> eps1.txtt || echo "command14 failed" >> eps1.txtt
python optimize_mask_cifar.py --anp-eps 6.4 >> eps1.txtt || echo "command15 failed" >> eps1.txtt
python optimize_mask_cifar.py --anp-eps 6.8 >> eps1.txtt || echo "command16 failed" >> eps1.txtt
python optimize_mask_cifar.py --anp-eps 7.2 >> eps1.txtt || echo "command17 failed" >> eps1.txtt
python optimize_mask_cifar.py --anp-eps 7.6 >> eps1.txtt || echo "command18 failed" >> eps1.txtt
python optimize_mask_cifar.py --anp-eps 8.0 >> eps1.txtt || echo "command19 failed" >> eps1.txtt
python optimize_mask_cifar.py --anp-eps 8.4 >> eps1.txtt || echo "command20 failed" >> eps1.txtt
python optimize_mask_cifar.py --anp-eps 8.8 >> eps1.txtt || echo "command21 failed" >> eps1.txtt
python optimize_mask_cifar.py --anp-eps 9.2 >> eps1.txtt || echo "command22 failed" >> eps1.txtt
python optimize_mask_cifar.py --anp-eps 9.6 >> eps1.txtt || echo "command23 failed" >> eps1.txtt
python optimize_mask_cifar.py --anp-eps 10.0 >> eps1.txtt || echo "command24 failed" >> eps1.txtt
